config/routes.rb
require 'resque/server'

Tagore::Application.routes.draw do
  resources :provisions

  resources :services do
    member do
      post 'deploy'
    end
  end

  resources :resources

  mount Resque::Server.new, :at => "/resque"

  root :to => 'services#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :description, :name, :repo

  validates :name, :uniqueness => { :case_sensitive => false }
  validates :name, :format => { :with => /\A[a-zA-Z]+\z/, :message => "Only letters allowed" }

  has_many :resources
  has_many :deploys
  has_many :provisions

  DEPLOY_COMMAND = "deploy"
  PROVISION_ROUTER_COMMAND = "nginx_provision"

  before_save do
    self.name.downcase!
  end

  def deploy!
    $REDIS.publish(DEPLOY_COMMAND, "#{self.id.to_s} HEAD")
  end

  def started!(machine_id, port)
    Port.create(:machine_id => machine_id, :service_id => self.id)
    $REDIS.publish(PROVISION_ROUTER_COMMAND, "update")
  end

  def stopped!(machine_id)
    Port.where(:machine_id => machine_id, :service_id => self.id).each(&:destroy)
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.json
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.json do
        ret = @services.map do |s|
          {
            :subdomain => s.name,
            :service => s.host_prts
          }
        end
        render json: ret
      end
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find_by_name(params[:name])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  def deploy
    @service = Service.find(params[:id])
    @service.deploy!

    return redirect_to :back
  end

  def started
    @service = Service.find(params[:id])
    @service.started!(params[:machine_id], params[:ports])

    head(:ok)
  end

  def stopped
    @service = Service.find(params[:id])
    @service.stopped!(params[:machine_id], params[:ports])

    head(:ok)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.haml
= form_for(@service) do |f|
  - if @service.errors.any?
    #error_explanation
      %h2
        = pluralize(@service.errors.count, "error")
        prohibited this service from being saved:
      %ul
        - @service.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name

    %p
      This will be lowercased and also be used as the subdomain which
      we internally refer to.

    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :repo
    %br/
    = f.text_field :repo

  .actions
    = f.submit "Create", :class => "btn btn-success"
    = link_to 'Cancel', services_path, :class => "btn btn-danger"

app/views/services/edit.html.haml
.row
  .span12
    %h1 Editing service
.row
  .span12
    = render 'form'

= link_to 'Show', @service

app/views/services/index.html.haml
- content_for :menu do
  %ul.nav
    %li= link_to 'New Service', new_service_path, :class => "btn btn-primary"

.row
  .span12
    %h1 Services
  .span12
    %table.table.table-bordered
      %thead
        %tr
          %th Name
          %th Status

      %tbody
        - @services.each do |service|
          %tr
            %td= link_to service.name, service_path(service)
            %td

app/views/services/new.html.haml
.row
  .span12
    %h1 New service

.row
  .span12
    = render 'form'

app/views/services/show.html.haml
- content_for :menu do
  %ul.nav
    %li= link_to 'Edit', edit_service_path(@service)

  %ul.pull-right.nav
    %li= render "resources/form"
    %li= button_to 'Deploy', deploy_service_path(@service), :class => "btn btn-primary"

.row
  .span10
    %h1= @service.name

.row
  .span12
    %pre= @service.repo

.row
  .span12
    %p= @service.description

%hr/

.row
  .span12
    %h2 Procfile

  %code.span12
    web:     bundle exec thin start -p $PORT
    %br/
    worker:  bundle exec rake resque:work

%hr/

.row
  .span8
    %h2 Resources
  .span4


  .span12
    %table.table.table-bordered
      %thead
        %tr
          %th Resource
          %th Host
          %th Data
      - @service.resources.each do |r|
        %tr
          %td= r.class.to_s
          %td= r.machine.ip_address
          %td
            %pre= pp r.data

%hr/

.row
  .span10
    %h2 Deploys

  .span2

  .span12
    %table.table
      - @service.deploys.each do |d|
        %tr
          %td= d.commit